routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\ShopController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


Auth::routes();



Route::group(['middleware' => ['auth','refresh.resources']], function(){
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::resource('shop', ShopController::class);

});


Route::get('/guestlogin', function (){
    Auth::loginUsingId(1);
    return redirect()->route('home');
});

Route::get('/guestlogout', function (){
    Auth::logout();

    request()->session()->invalidate();

    request()->session()->regenerateToken();

    return redirect('/');
});

app/Models/Building.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Building extends Model
{
    use HasFactory;

    protected $fillable = ['type'];

    public function users()
    {
        return $this->belongsToMany(User::class)->withPivot('qty');
    }

    public function resource()
    {
        return $this->hasOne(Resource::class);
    }
    public function getResourceName()
    {
        return Str::of($this->resource()->first()->type)->title();
    }

}

app/Models/Resource.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Resource extends Model
{
    use HasFactory;

    protected $fillable = ['type'];

    public function users()
    {
        return $this->belongsToMany(User::class)->withPivot('qty');
    }

    public function building()
    {
        return $this->belongsTo(Building::class);
    }

}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public function buildings()
    {
        return $this->belongsToMany(Building::class)->withPivot('qty');
    }

    public function resources()
    {
        return $this->belongsToMany(Resource::class)->withPivot('qty');
    }

    public function ownedBuildingsQty() : array
    {
        $rel = $this->belongsToMany(Building::class)->withPivot('qty')->where('qty','!=',0)->get();
        return $rel->pluck('pivot.qty','type')->toArray();
    }
}

app/helpers.php
<?php

use App\Models\User;
use App\Services\ResourceService;
use Illuminate\Support\Facades\Auth;
use phpDocumentor\Reflection\Types\Collection;


function getCurrUser(){
    return User::find(Auth::id());
//    return auth()->user(); //wont refresh accordingly
}
/**
 * Create a new controller instance.
 * @return Collection
 */

function getCurrUserResources(){
    return getCurrUser()->resources->pluck('pivot.qty','type');
}


function getCurrUserBuildings(){
    return getCurrUser()->buildings->pluck('pivot.qty','type');
}

function getResourcesYields() {
    $rs = new ResourceService();
    return  $rs->getResourcesYields();
}

app/Http/Controllers/BuildingController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class BuildingController extends Controller
{
    //
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $resources = getCurrUserResources();
        $buildings = getCurrUserBuildings();
        return view('home',['resources' => $resources,
                                        'buildings' => $buildings]);

    }
}

app/Http/Controllers/ShopController.php
<?php

namespace App\Http\Controllers;

use App\Models\Building;
use App\Models\Resource;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ShopController extends Controller
{

//    public function __construct()
//    {
//        $this->middleware('auth');
//    }


    public function index()
    {
        return view('shop.index',['buildings' => Building::all()]);
    }

    public function update($buildingId)
    {
        $building = Building::find($buildingId);
        $requiredAmount = $building->cost;
        $requiredType = $building->resource->type;

        $requiredResourceTypeId = Resource::where('type',$requiredType)->get()->first()->id;


        if ($requiredAmount <= getCurrUserResources()['minerals'] ) //TODO: static currency
        {
            $userHasBuilding = getCurrUser()
                ->buildings()
                ->where('user_id',getCurrUser()->id)
                ->where('building_id',$buildingId)
                ->get();

            if (count($userHasBuilding) == 0)
            {
                getCurrUser()->buildings()->attach($buildingId,['qty'=> '1']);
            } else {
                getCurrUser()->buildings()->where('type',$building->type)->first()->pivot->increment('qty');
            }

            $amountLeft = getCurrUserResources()['minerals'] - $requiredAmount ;

            getCurrUser()->resources()->updateExistingPivot(getCurrUser()->resources()->where('resource_id',1)->get(), [ //TODO:hardcoded value for currency
                'qty' => $amountLeft,
            ]);



            return redirect()->route('home')->with('message','purchase successful');
        }

        return back()->with('message','insufficient funds');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
@if(Session::has('message'))
    <p class="alert alert-success">{{ Session::get('message') }}</p>
@endif
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Buildings') }}</div>

                <div class="card-body">
{{--                    @if (session('status'))--}}
{{--                        <div class="alert alert-success" role="alert">--}}
{{--                            {{ session('status') }}--}}
{{--                        </div>--}}
{{--                    @endif--}}
{{--                    --}}{{-- {{ __('You are logged in!') }} --}}
                    <div class="py-1">
                        <img style="width: 50px" height="85px" src="{{ asset('images/mineral_mine2.jpg') }}" alt=""><span>{{ $buildings['mineral mine'] }} QTY</span>
                    </div>
                    <div class="py-1">
                        <img style="width: 50px" height="85px" src="{{ asset('images/refinery2.jpg') }}" alt=""><span> {{ $buildings['gas refinery'] }} QTY</span>
                    </div>

                </div>
            </div>
        </div>

        <div class="card">
            <div  class="card-header">{{ __('Dashboard') }}</div>
            <div class="card-body">
                <div class="py-1">
                    <img style="width: 50px" height="85px" src="{{ asset('images/minerals2.png') }}" alt="">
                    <div class="text-center d-inline-block">
                        <div class="m-1 ">{{ $resources['minerals'] }} QTY</div>
                        <div class="m-1">Yield: {{ getResourcesYields()['mineral mine']  }}/min</div>
                    </div>
                </div>
                <div class="py-1">
                    <img style="width: 50px" height="85px" src="{{ asset('images/gas.jpg') }}" alt="">
                    <div class="text-center d-inline-block">
                        <div class="m-1 ">{{ $resources['vespene gas'] }} QTY</div>
                        <div class="m-1">Yield: {{ getResourcesYields()['gas refinery'] ?? 0 }}/min</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <a href="{{ route('shop.index') }}">
                    Shop
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/shop/index.blade.php
@extends('layouts.app')


@section('content')



<div class="container">
    @if(Session::has('message'))
        <p class="alert alert-danger">{{ Session::get('message') }}</p>
    @endif
    <h1>Shop</h1>

    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Building</th>
            <th scope="col">Price</th>
            <th scope="col">Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach( $buildings as $key => $building)
            <tr>
                <th scope="row">{{ ++$key }}</th>
                <td>{{$building->type}}</td>
                <td>{{$building->cost}}</td>
                <td>
                    <form action="{{ route('shop.update',$building->id) }}" method="post">
                        @csrf
                        @method('put')
                        <button type="submit">Buy</button>
                    </form>
                </td>
            </tr>
        @endforeach

        </tbody>
    </table>
</div>

@endsection